import type { DepartmentId } from "./enquiry";

export type ProductCategory =
  | "men"
  | "women"
  | "kids"
  | "ethnics"
  | "accessories";

export interface Product {
  id: string;
  brand: string;
  name: string;
  features: string;
  category: ProductCategory;
  department: DepartmentId;
  image: string;
  badge: string;
  badgeTone: "dark" | "green" | "orange";
  // price: number;
  // mrp?: number;
  // discountLabel?: string;
  sizeFieldLabel: string;
  sizes: string[];
}

export const products: Product[] = [
  // =====================================================
  // MEN
  // =====================================================

  {
    id: "mens-cargo-pants",
    brand: "Trendz Plus",
    name: "Cargo Pants",
    features: "Comfort Fit • Multiple Pockets • Everyday Wear",
    category: "men",
    department: "mens",
    image: "/MENS/CARGOPANTS.png",
    badge: "POPULAR",
    badgeTone: "dark",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Waist in stock",
    sizes: ["30", "32", "34", "36", "38"],
  },

  {
    id: "mens-casual-shirt",
    brand: "Trendz Plus",
    name: "Casual Shirt",
    features: "Regular Fit • Comfortable Fabric • Everyday Wear",
    category: "men",
    department: "mens",
    image: "/MENS/CASUALSHIRTMENS.png",
    badge: "BEST SELLER",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-formal-pant",
    brand: "Trendz Plus",
    name: "Formal Pant",
    features: "Smart Fit • Formal Finish • Office Wear",
    category: "men",
    department: "mens",
    image: "/MENS/FORMALPANT.png",
    badge: "OFFICE PICK",
    badgeTone: "dark",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Waist in stock",
    sizes: ["30", "32", "34", "36", "38"],
  },

  {
    id: "mens-formal-shirt",
    brand: "Trendz Plus",
    name: "Formal Shirt",
    features: "Smart Fit • Easy Care • Office Ready",
    category: "men",
    department: "mens",
    image: "/MENS/FORMALSHIRT.png",
    badge: "POPULAR",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-graphic-tee",
    brand: "Trendz Plus",
    name: "Graphic Tee",
    features: "Soft Fabric • Modern Print • Casual Wear",
    category: "men",
    department: "mens",
    image: "/MENS/GRPAHICTEEMENS.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-kurta",
    brand: "Trendz Plus",
    name: "Men's Kurta",
    features: "Comfort Fabric • Traditional Style • Festive Wear",
    category: "men",
    department: "mens",
    image: "/MENS/KURTA.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-polo-tee",
    brand: "Trendz Plus",
    name: "Polo Tee",
    features: "Classic Collar • Comfortable Fit • Everyday Wear",
    category: "men",
    department: "mens",
    image: "/MENS/POLOTEE.png",
    badge: "EVERYDAY PICK",
    badgeTone: "dark",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-sports-pants",
    brand: "Trendz Plus",
    name: "Sports Pants",
    features: "Stretch Fabric • Comfortable Fit • Active Wear",
    category: "men",
    department: "mens",
    image: "/MENS/SPORTSPANTS.png",
    badge: "ACTIVE PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Waist in stock",
    sizes: ["30", "32", "34", "36", "38"],
  },

  {
    id: "mens-sports-tee",
    brand: "Trendz Plus",
    name: "Sports Tee",
    features: "Lightweight Fabric • Active Fit • Sports Wear",
    category: "men",
    department: "mens",
    image: "/MENS/SPORTSTEE.png",
    badge: "ACTIVE PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "mens-traditional-set",
    brand: "Trendz Plus",
    name: "Traditional Wear",
    features: "Classic Indian Style • Comfortable Fabric • Festive Ready",
    category: "men",
    department: "mens",
    image: "/MENS/TRADS.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  // =====================================================
  // WOMEN
  // =====================================================

  {
    id: "womens-bodycon",
    brand: "Trendz Plus",
    name: "Bodycon Dress",
    features: "Modern Fit • Comfortable Fabric • Party Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/BODYCON.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-casual-shirt",
    brand: "Trendz Plus",
    name: "Casual Shirt",
    features: "Relaxed Fit • Comfortable Fabric • Everyday Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/CASUALSHIRT.png",
    badge: "EVERYDAY PICK",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-coord-set",
    brand: "Trendz Plus",
    name: "Co-ord Set",
    features: "Matching Set • Modern Style • Easy Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/CORDSET.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-formal",
    brand: "Trendz Plus",
    name: "Formal Wear",
    features: "Smart Fit • Elegant Style • Office Ready",
    category: "women",
    department: "womens",
    image: "/LADIES/FORMAL.png",
    badge: "OFFICE PICK",
    badgeTone: "dark",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-graphic-tee",
    brand: "Trendz Plus",
    name: "Graphic Tee",
    features: "Soft Fabric • Stylish Print • Casual Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/GRAPHICTEE.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-jeans",
    brand: "Trendz Plus",
    name: "Women's Jeans",
    features: "Comfort Stretch • Modern Fit • Everyday Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/JEANS.png",
    badge: "BEST SELLER",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Waist in stock",
    sizes: ["26", "28", "30", "32", "34"],
  },

  {
    id: "womens-night-suit",
    brand: "Trendz Plus",
    name: "Night Suit",
    features: "Soft Fabric • Relaxed Fit • Comfortable Sleepwear",
    category: "women",
    department: "womens",
    image: "/LADIES/NIGHTSUIT.png",
    badge: "COMFORT PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["M", "L", "XL", "XXL"],
  },

  {
    id: "womens-pants",
    brand: "Trendz Plus",
    name: "Women's Pants",
    features: "Comfort Fit • Versatile Style • Everyday Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/PANTS.png",
    badge: "POPULAR",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Waist in stock",
    sizes: ["26", "28", "30", "32", "34"],
  },

  {
    id: "womens-tank-top",
    brand: "Trendz Plus",
    name: "Tank Top",
    features: "Lightweight Fabric • Comfortable Fit • Casual Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/TANKTOP.png",
    badge: "EVERYDAY PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "womens-tops",
    brand: "Trendz Plus",
    name: "Women's Tops",
    features: "Trendy Style • Comfortable Fabric • Everyday Wear",
    category: "women",
    department: "womens",
    image: "/LADIES/TOPS.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  // =====================================================
  // ETHNIC WEAR
  // =====================================================

  {
    id: "ethnic-anarkali",
    brand: "Trendz Plus",
    name: "Anarkali",
    features: "Elegant Ethnic Wear • Festive Style • Comfortable Fit",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/anarkali.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "ethnic-dupatta",
    brand: "Trendz Plus",
    name: "Dupatta",
    features: "Traditional Design • Versatile Styling • Festive Wear",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/duppta.png",
    badge: "ETHNIC PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Styles in stock",
    sizes: ["Free Size"],
  },

  {
    id: "ethnic-kids-set",
    brand: "Trendz Plus",
    name: "Kids Ethnic Wear",
    features: "Comfortable Fabric • Traditional Style • Festive Ready",
    category: "ethnics",
    department: "kids",
    image: "/FESTIVE/kidd.png",
    badge: "KIDS PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Ages",
    sizes: ["2-4Y", "5-7Y", "8-10Y", "11-13Y"],
  },

  {
    id: "ethnic-kids-traditional",
    brand: "Trendz Plus",
    name: "Kids Traditional Wear",
    features: "Festive Style • Soft Fabric • Comfortable Fit",
    category: "ethnics",
    department: "kids",
    image: "/FESTIVE/kidddddddddd.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Ages",
    sizes: ["2-4Y", "5-7Y", "8-10Y", "11-13Y"],
  },

  {
    id: "ethnic-kurta",
    brand: "Trendz Plus",
    name: "Ethnic Kurta",
    features: "Classic Design • Comfortable Fabric • Festive Wear",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/KURTA.png",
    badge: "ETHNIC PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "ethnic-ladies-wear",
    brand: "Trendz Plus",
    name: "Ladies Ethnic Wear",
    features: "Elegant Style • Comfortable Fit • Traditional Wear",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/ladies.png",
    badge: "TRENDING",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "ethnic-mens-traditional",
    brand: "Trendz Plus",
    name: "Embroidered Lehenga Choli Set",
    features: "Classic Indian Style • Festive Ready • Comfortable Fit",
    category: "ethnics",
    department: "mens",
    image: "/FESTIVE/lads.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL", "XXL"],
  },

  {
    id: "ethnic-lehenga",
    brand: "Trendz Plus",
    name: "Lehenga",
    features: "Festive Collection • Elegant Design • Occasion Wear",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/lehenga.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "ethnic-short-kurti",
    brand: "Trendz Plus",
    name: "Short Kurti",
    features: "Lightweight Fabric • Modern Ethnic • Everyday Wear",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/short kurti.png",
    badge: "POPULAR",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  {
    id: "ethnic-traditional",
    brand: "Trendz Plus",
    name: "Traditional Wear",
    features: "Indian Ethnic Style • Occasion Wear • Comfortable Fabric",
    category: "ethnics",
    department: "womens",
    image: "/FESTIVE/TRADS.png",
    badge: "FESTIVE PICK",
    badgeTone: "orange",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["S", "M", "L", "XL"],
  },

  // =====================================================
  // ACCESSORIES
  // =====================================================

  {
    id: "accessory-baby-carry",
    brand: "Trendz Plus",
    name: "Baby Carry",
    features: "Useful Everyday Accessory • Practical • Easy to Carry",
    category: "accessories",
    department: "kids",
    image: "/ACESSORIES/Babycarry.png",
    badge: "POPULAR",
    badgeTone: "dark",
 // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-belt",
    brand: "Trendz Plus",
    name: "Belt",
    features: "Classic Design • Durable Finish • Everyday Accessory",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/BELT.png",
    badge: "BEST SELLER",
    badgeTone: "dark",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes",
    sizes: ["M", "L", "XL"],
  },

  {
    id: "accessory-caps",
    brand: "Trendz Plus",
    name: "Caps",
    features: "Casual Style • Comfortable Fit • Everyday Wear",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/CAPS.png",
    badge: "POPULAR",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Size",
    sizes: ["Free Size"],
  },

  {
    id: "accessory-gift-hamper",
    brand: "Trendz Plus",
    name: "Gift Hamper",
    features: "Ready to Gift • Curated Collection • Special Occasions",
    category: "accessories",
    department: "womens",
    image: "/ACESSORIES/GIFT HAMPER.png",
    badge: "GIFT PICK",
    badgeTone: "orange",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-perfume",
    brand: "Trendz Plus",
    name: "Perfume",
    features: "Long Lasting Fragrance • Everyday Use • Premium Feel",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/PERFUME.png",
    badge: "POPULAR",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-pillow",
    brand: "Trendz Plus",
    name: "Pillow",
    features: "Soft Comfort • Home Essential • Everyday Use",
    category: "accessories",
    department: "womens",
    image: "/ACESSORIES/PILLOW AGAIN BUT DIFF.png",
    badge: "HOME PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["Standard"],
  },

  {
    id: "accessory-pillow-ig",
    brand: "Trendz Plus",
    name: "Decorative Pillow",
    features: "Soft Feel • Decorative Design • Home Accessory",
    category: "accessories",
    department: "womens",
    image: "/ACESSORIES/PILLOW IG.png",
    badge: "HOME PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["Standard"],
  },

  {
    id: "accessory-small-item",
    brand: "Trendz Plus",
    name: "BathRobe",
    features: "Everyday Accessory • Compact • Easy to Carry",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/Bathrobe.png",
    badge: "NEW",
    badgeTone: "orange",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-socks",
    brand: "Trendz Plus",
    name: "Socks",
    features: "Soft Fabric • Comfortable Fit • Everyday Essential",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/SOCKS.png",
    badge: "EVERYDAY PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes",
    sizes: ["Free Size"],
  },

  {
    id: "accessory-swim",
    brand: "Trendz Plus",
    name: "Swim Wear",
    features: "Comfortable Fabric • Active Lifestyle • Easy Movement",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/SWIMMM.png",
    badge: "ACTIVE PICK",
    badgeTone: "green",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Sizes in stock",
    sizes: ["M", "L", "XL"],
  },

  {
    id: "accessory-tie",
    brand: "Trendz Plus",
    name: "Tie",
    features: "Classic Design • Formal Accessory • Office Ready",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/TIE.png",
    badge: "FORMAL PICK",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-umbrella",
    brand: "Trendz Plus",
    name: "Umbrella",
    features: "Compact Design • Easy Carry • Everyday Utility",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/UMBRELLA.png",
    badge: "EVERYDAY PICK",
    badgeTone: "green",
 // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-utility",
    brand: "Trendz Plus",
    name: "Baby Care Essentials",
    features: "Practical Design • Everyday Use • Easy to Carry",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/Babycare.png",
    badge: "NEW",
    badgeTone: "orange",
    // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

  {
    id: "accessory-wallet",
    brand: "Trendz Plus",
    name: "Wallet",
    features: "Compact Design • Multiple Compartments • Everyday Carry",
    category: "accessories",
    department: "mens",
    image: "/ACESSORIES/WALLET.png",
    badge: "BEST SELLER",
    badgeTone: "dark",
     // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
    sizeFieldLabel: "Available",
    sizes: ["One Size"],
  },

{
  id: "kids-babies",
  brand: "Trendz Plus",
  name: "Baby Essentials",
  features: "Soft Fabric • Comfortable Fit • Everyday Baby Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/BABIES.png",
  badge: "BABY PICK",
  badgeTone: "green",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["0-6M", "6-12M", "1-2Y", "2-3Y"],
},

{
  id: "kids-bodysuit",
  brand: "Trendz Plus",
  name: "Baby Bodysuit",
  features: "Soft Cotton • Easy Wear • Comfortable Fit",
  category: "kids",
  department: "kids",
  image: "/KIDS/BODYSUIT.png",
  badge: "BABY PICK",
  badgeTone: "green",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["0-6M", "6-12M", "1-2Y"],
},

{
  id: "kids-casual-boys",
  brand: "Trendz Plus",
  name: "Boys Casual Wear",
  features: "Comfortable Fabric • Casual Style • Everyday Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/CASUALBOYS.png",
  badge: "POPULAR",
  badgeTone: "dark",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y", "11-12Y"],
},

{
  id: "kids-casual-girl",
  brand: "Trendz Plus",
  name: "Girls Casual Wear",
  features: "Soft Fabric • Trendy Style • Everyday Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/CASUALGIRL.png",
  badge: "TRENDING",
  badgeTone: "orange",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y", "11-12Y"],
},

{
  id: "kids-frock",
  brand: "Trendz Plus",
  name: "Girls Party Frock",
  features: "Festive Style • Comfortable Lining • Party Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/FROK.png",
  badge: "PARTY PICK",
  badgeTone: "orange",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
},

{
  id: "kids-ethnic-set",
  brand: "Trendz Plus",
  name: "Kids Casual Wear",
  features: "Traditional Style • Festive Ready • Comfortable Fit",
  category: "kids",
  department: "kids",
  image: "/KIDS/KID.png",
  badge: "FESTIVE PICK",
  badgeTone: "orange",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
},

{
  id: "kids-girls-lehenga",
  brand: "Trendz Plus",
  name: "Girls Lehenga Set",
  features: "Embroidered Top • Flared Skirt • Festive Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/kidd.png",
  badge: "FESTIVE PICK",
  badgeTone: "orange",
 // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
},

{
  id: "kids-traditional-set",
  brand: "Trendz Plus",
  name: "Embroided Girls Lehenga Set",
  features: "Traditional Design • Comfortable Fabric • Occasion Wear",
  category: "kids",
  department: "kids",
  image: "/KIDS/kiddd.png",
  badge: "FESTIVE PICK",
  badgeTone: "orange",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
},

{
  id: "kids-party-wear",
  brand: "Trendz Plus",
  name: "Boy Traditional Set",
  features: "Occasion Wear • Elegant Design • Comfortable Fit",
  category: "kids",
  department: "kids",
  image: "/KIDS/kidddddddddd.png",
  badge: "PARTY PICK",
  badgeTone: "orange",
   // price: 999,
    // mrp: 1499,
    // discountLabel: "33% OFF",
  sizeFieldLabel: "Ages",
  sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
},


];